### ISSUE TITLE
What happen if randoString return a filename's string that exists?

### ISSUE THREAD

**Issue by radar155** [andrewrk/node-multiparty#103]
When i upload a file, xxx.jpg for example, multiparty creates a 18 characters string in the specified uploaddir as filename. What happen if in my directory exists a file with the same random generated string name?? it seems that this rare case is not handled!

**Comment by andrewrk** [comment]
It's 18 bytes of randomness, not 18 characters. The chance of this happening is 1 out of 22300745198530623141535718272648361505980416. If you wrote 1 million files to disk per second, you would have to do that for `5 * 10^29` years to have a 50% chance of a collision. Meanwhile, the sun will destroy the earth in `5 * 10^9` years.

**Comment by dougwilson** [comment]
For the original question, the answer is: "it'll be overwritten".

If you can document this occurring, we can look into it, but as @andrewrk notes, this is 18 bytes of randomness (using cryptographically randomness, in fact), which translates to 144 bits. Since a filename cannot contain (in a portable way) any byte, we base64 those 18 bytes, which makes the ending file name sting longer. In addition to the 144 bits of randomness, we also take the original file extension, so that is almost like an extra bit added there.

Potentially we could open the file with the `wx` flag so it would error if a file with the same name already existed, but eh. There is also another really important point: the `uploadDir` is _only meant to be a temporary directory_, i.e. your Node.js app is expected to `fs.rename` any file you want to keep out of the `uploadDir` (and that directory should also not survive machine reboots, should havea  periodic cron job cleaning it out, etc.).

**Comment by radar155** [comment]
i understand that the possbility that this happen is very very rare. But simply it can happen. Even if the uploaddir is meant to be a temp dir, if my client upload 2 files with the same extension, 1 out of 22300745198530623141535718272648361505980416 you can have a problem..ok it's VERY rare.. Anyway, fs.exists is so expensive?

**Comment by dougwilson** [comment]
`fs.exists` doesn't help here with this timeline of events:

1. pick a random file name
2. check if it exists
3. no, it doesn't, use that to write the file
4. another process picks the same file name and noted it didn't exist and uses it
5. now you overwrite this

this is actually the reason `fs.exists` is being deprecated in node.js core (already is in io.js) because it's an antipattern to think you've prevented race conditions...

one may argue the sequence of events above is rare. yes, but so is picking the same file name from 144 bits of randomness.

I provided the only good solution above: we can open with the flags `wx` and if the file existed, error out the entire request and let the client retry.

**Comment by dougwilson** [comment]
@andrewrk what are your thoughts on me having the code open with `wx` and error out if it tries to trample an existing file?

**Comment by andrewrk** [comment]
@dougwilson Sounds good.

**Comment by dougwilson** [comment]
Done :)
