### ISSUE TITLE
Request aborted thrown despite error listeners attached

### ISSUE THREAD

**Issue by kolpax** [andrewrk/node-multiparty#133]
I am experiencing that if the upload is killed by a timeout on a proxy or a http server Multiparty throws a `Request aborted` un-handled error exception - despite the fact that I have on('error', ...) handlers for both the form and the parts.

According to the documentation the error should not have been thrown if I have error listeners attached.
Any help would be greatly appreciated!

```
Error: Request aborted
  at IncomingMessage.onReqAborted (/.../node_modules/multiparty/index.js:183:17)
  at emitNone (events.js:80:13)
  at IncomingMessage.emit (events.js:179:7)
  at abortIncoming (_http_server.js:280:11)
  at Socket.serverSocketCloseListener (_http_server.js:293:5)
  at emitOne (events.js:95:20)
  at Socket.emit (events.js:182:7)
  at TCP._onclose (net.js:469:12)
```

**Comment by ronag** [comment]
Same issue with:

```javascript
  const form = new multiparty.Form()

  const mediaId = `media.${cuid()}`

  _((push) => {
    form.on('part', part => push(null, part))
    // TODO: What if auto field parsing fails?
    form.on('field', (name, value) => push(null, { name, value }))
    form.on('error', err => {
      logger.debug(err)
      // Do nothing..
    })
    form.on('close', () => push(null, _.nil))
    form.parse(req)
  })
```

**Comment by dougwilson** [comment]
Hi @kolpax, I assume you have figured out your issue since you closed the issue. Please let me know if you haven't.

Hi @ronag, I like you use of the `highland` module, but unfortunately by the time your `.each` is executed with a `part`, there has been some passes around the event loop, and opportunity for an `error` event to be emitted before you attach the error listener.
